apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruby-app
  template:
    metadata:
      labels:
        app: ruby-app
    spec:
      containers:
      - name: ruby-app
        image: docker.io/waveywaves/mirrord-ruby-example:v1
        ports:
        - containerPort: 4567
        env:
        - name: REDIS_URL
          value: redis://redis-service:6379
---
apiVersion: v1
kind: Service
metadata:
  name: ruby-app
spec:
  selector:
    app: ruby-app
  ports:
  - protocol: TCP
    port: 4567
    targetPort: 4567
  type: LoadBalancer
